---
# tasks file for apache

- name: Install Apache
  yum:
    name: httpd
    state: latest
    update_cache: true

- name: Ensure that HTTP is enabled
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Ensure that HTTPS is enabled
  firewalld:
    service: https
    permanent: true
    state: enabled
