---
# tasks file for apache

- name: Install Apache
  yum:
    name: httpd
    state: latest
    update_cache: true

- name: Start Apache
  service:
    name: httpd
    state: started

- name: Enable Apache on boot
  service:
    name: httpd
    enabled: true
