---
- hosts: tag_owner_ans6:&tag_os_windows
  tasks:
    - name: Ping windows machines
      win_ping:

    - name: Install all Windows updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
      register: update_result

    - name: Reboot if needed
      win_reboot:
      when: update_result.reboot_required
      
