---
# tasks file for mysql

- name: Install MySQL yum repository
  yum:
    name: https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    state: present

- name: Install MySQL Server
  yum:
    name: mysql-community-server
    state: latest
    update_cache: true

- name: Start MySQL service
  service:
    name: mysql
    status: started

- name: Enable MySQL service on boot
  service:
    name: mysql
    enabled: true
